#!/bin/sh

wget -O - https://raw.githubusercontent.com/mufkuw/scripts/main/install_ols | bash

mkdir /var/www/ps >> /dev/null
mkdir /var/www/ps/a2 >> /dev/null
mkdir /var/www/ps/db >> /dev/null
mkdir /var/www/ps/cert >> /dev/null
mkdir /var/www/ps/log >> /dev/null
mkdir /var/www/ps/html >> /dev/null

#echo transfering data to single folder version
mysql -e  "CREATE DATABASE ps;"

mv /var/lib/mysql/ps /var/www/db/
ln -s /var/www/db/ps /var/lib/mysql/ps
ln -s /var/www/ps/html $HOME/ps

apt-get install unzip -y
wget https://download.prestashop.com/download/releases/prestashop_1.7.8.6.zip
unzip prestashop_1.7.8.6.zip -d $HOME/ps
